unit DContacts.Models.Entities.Contact;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('contact')]
  TContact = class
  strict private
    [Column('id', [cpPrimaryKey])]
    [AutoGenerated]
    FId: Integer;
    [Column('nome', [])]
    FNome: String;
    [Column('email', [])]
    FEmail: String;
    [Column('telefone', [])]
    FTelefone: String;
  public
    property Id: Integer read FId write FId;
    property Nome: String read FNome write FNome;
    property Email: String read FEmail write FEmail;
    property Telefone: String read FTelefone write FTelefone;
  end;

implementation

end.
